---
# tasks file for elk
# vars ไฟล์จะโดนดูดเข้ามาอัตโนมัติทันทีชื่อต้องตาม format yml แท้ๆ ห้ามมีจุด ต้องใช้แบบ key pair indent :
# - name: fdsfsd
#   debug:
#     msg: "{{kibana_password}}"

- name: "git clone project MeetU {{kibana.password}}"
  become: no
  git:
    repo: "https://github.com/wdrdres3qew5ts21/MeetU.git"
    dest: "~/meetu"
    update: yes

- name: Create network
  docker_network:
    name: meetu_elastic

# ต้องใช้ Certificate จาก Let's Encrypt มาเชื่อมกับ container ของเราผ่าน volume
- name: "Start Elasticsearch Docker"
  docker_container:
    name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    state: present
    restart: yes
    published_ports:
      - "9200:9200"
    networks: 
      - name: meetu_elastic
    volumes:
      - meetu_data01
    ulimits:
      - "memlock:-1:-1"

    

    





# - name: "Start Kibana Docker"
#   docker_container:
#     image: docker.elastic.co/kibana/kibana:7.7.0
#     name: elasticsearch1
#     state: present
    




# - name: Change Kibana Password API
#   uri:
#     url: "https://localhost:9200/_security/user/kibana/_password?pretty"
#     follow_redirects: none
#     method: POST
#     user: elastic
#     password: PleaseChangeMe
#     validate_certs: no
#     force_basic_auth: yes
#     body_format: json
#     body: >
#       { "password": "{{kibana_password}}" }
#   register: _result
#   until: _result.status == 200
#   retries: 20
#   delay: 5
