---
# tasks file for revoke_certificate
  # ansible นับ tag แบบบางส่วน คือ tag ที่สืบทอดมาตอนนี้จะเป็น การเพิ่ม tag ลงไป
  # ** บังคับใส่ tag เท่านั้นถึงจะทำงาน
- name: "[Staging] Revoke Certificate: {{ certificate_server_name }}"
  # command: echo "staging" 
  command: certbot revoke --staging --non-interactive --cert-path /etc/letsencrypt/live/{{ certificate_server_name }}/cert.pem 
  when: deployment_plan == "staging"

- name: "[Production] Revoke Certificate: {{ certificate_server_name }}"
  # command: echo "production"
  command: certbot revoke --non-interactive --cert-path /etc/letsencrypt/live/{{ certificate_server_name }}/cert.pem 
  when: deployment_plan == "production"

  