---
# tasks file for nginx_native_ssl
- name: Install Epel-Release
  yum:
    name: epel-release
    state: present

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start Nginx Daemon and boot on start
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Install certbot & python3-certbot-nginx
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - certbot
    - python3-certbot-nginx


- name: Setup Nginx SSL Template
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    force: yes

- name: Automate Generate Certificate and install it for Nginx
  command: "certbot --non-interactive -d {{server_name}}   -m username@example.com  --agree-tos"  


# - name: Generate Certificate only for Nginx
#   command: certbot certonly --nginx

# - name: Automatic Renewal Certificate
#   command: echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null





