---
# tasks file for generate_certificate
- name: Install certbot & python3-certbot-nginx
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - certbot
    - python3-certbot-nginx

  # การ generate certificate นั้นเราไม่ต้องการให้ไปติดตั้งบน web server ใดๆเพียงแต่ต้องการ cert ที่รับรองแล้ว
  # ดังนั้น concept ในการทำงานคือใช้ mode standalone เท่านั้นโดยการทำงานจะสั่งไปยัง API ของ Let Encrypt 
  # แล้วจะติดต่อกลับมาหาเราที่ port 80 (ผ่าน Automate Certificate Management Enviroment Protocol RFC)
  # ซึ่งถ้าหาก domain ที่ยิงไป -d นั้นมีอยุ๋จริง ก็จะทำการเชื่อมต่อกันถ้าต่อเข้ามาได้ก็จะ generate certificate มาวางให้นั่นเอง
  # ในกรณีลบ Certificate เองคนที่จะลบได้ก็ต้องมี private key ด้วยเช่นกันแต่จะทำอย่างไร หาก Server เราโดนยึดไปแล้ว ?
  # วิธีการทำก็คือไปวัดที่ระดับ domain name server บน txt record เลยโดยให้เราใช้ code text พิเศษซึ่ง let encrypt 
  # เป็นคนส่งมาให้ไว้และถ้าหากเราเป้นเจ้าของ domain นั้นจริงเราก็จะสามารถคุม domain และเพิ่ม code ลับไปซึ่งเลา resolve
  # พอ let encrypt เจอ txt record พิเศษก็จะทราบว่านี่คือการบังคับสั่งลบ Certificate ก็จะโดน revoek นั่นเอง !!!

- name: "[Staging] Automate Generate Certificate and install it for Nginx"
  command: "certbot  --staging --nginx"  
  when: deployment_plan == "staging"

- name: "[Production] Automate Generate Certificate and install it for Nginx"
  command: "certbot --nginx" 
  when: deployment_plan == "production"

# - name: "[Staging] Automate Generate Certificate and install it for Nginx"
#   command: "certbot certonly --staging --non-interactive --standalone  --test-cert -d {{certificate_server_name}}   -m {{certificate_email_owner}}  --agree-tos"  
#   when: deployment_plan == "staging"

# - name: "[Production] Automate Generate Certificate and install it for Nginx"
#   command: "certbot certonly --non-interactive --standalone  --test-cert -d {{certificate_server_name}}   -m {{certificate_email_owner}}  --agree-tos"  
#   when: deployment_plan == "production"


- name: Setup Nginx SSL Template
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    force: yes