--- #centos8 edition
- hosts: elk_server
  become: yes
  become_method: sudo
  tasks:
  - name: VIEW ALL ANSIBLE FACT KEYS
    debug:
      msg: "{{ ansible_facts }}"

  - name: "Remove All Deprecated/ Install Docker"
    yum:
      name: "{{ item }}"
      state: absent
    loop:
      - docker 
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

  - name: "Start Docker Service"
    service:
      name: docker
      state: reloaded

  - name: "Add ansible_user (login user) to docker group"
    user:
      name: "{{ ansible_user }}"
      shell: /bin/bash
      groups: docker
      append: yes

  - name: "Install Git & Python"
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - git 
      - python3
      - python3-pip

  - name: "pip install docker-compose"
    pip:
      name: docker-compose
      state: present
      


  # - name: "CURL docker-compose"
  #   get_url: 
  #     url: "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}"
  #     dest: "/usr/local/bin/docker-compose"

  # - name: "Add permission to docker-compose inorder to run execute bin command"
  #   file:
  #     path: /usr/local/bin/docker-compose
  #     mode: +x

  # - name: "Add Symbolik Link to docker-compose bin /usr/bin"
  #   file: 
  #     state: link
  #     src: /usr/local/bin/docker-compose
  #     dest: /usr/bin/docker-compose


    


    
      
      
    
    

