- hosts: elk_server
  become: yes
  become_method: sudo
  roles: # ทำให้ ansible รันเฉพาะ tag ได้ถ้าไม่ระบุแท๊กก็จะรันทั้งมด ansible-playbook setup.yml -t docker 
    - {role: docker, tags: "docker"} 
    - {role: nginx_native_ssl, tags: "nginx_native_ssl"} 
    - {role: elk_ssl, tags: "elk_ssl"} 
    - {role: practice_logic, tags: "practice_logic"} 
